# Generated by Django 3.0.6 on 2021-01-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0002_downvote_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='question',
        ),
        migrations.DeleteModel(
            name='DownVote',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
    ]
